GRANT SELECT ON T1 TO USER1 WITH GTANT OPTION;
GRANT SELECT ON T1 TO USER2 WITH GTANT OPTION;
GRANT SELECT ON T1 TO USER3;
REVOKE SELECT ON T1 FROM USER2 CASCADE;

GRANT SELECT, INSERT, DELETE ON R TO Han, Lee WITH GRANT OPTION;
GRANT SELECT, INSERT ON R TO Park;
REVOKE GRANT OPTION FOR DELETE ON R FROM Lee;
REVOKE INSERT, DELETE ON R FROM Han CASCADE;

CREATE TABLE STUDENT (
    SNO INT NOT NULL,
    NAME VARCHAR(10),
    YEAR INT,
    DEPT VARCHAR(10),
    PRIMARY KEY (SNO)
);

INSERT INTO STUDENT VALUES (1001, 'KIM', 4, 'COMPUTER');
INSERT INTO STUDENT VALUES (1002, 'LEE', 4, 'COMPUTER');

CREATE VIEW CSTUDENT (SNO, NAME, YEAR) AS SELECT SNO, NAME, TEAR FROM STUDENT WHERE DEPT = 'COMPUTER';

UPDATE EMPLOYEE SET SALARY = SALARY * 1.1 WHERE DEPTNO (SELECT DEPTNO FROM DEPT WHERE DEP_NAME LIKE 'INSA%');

DELETE FROM STUDENT WHERE SCORE BETWEEN 70 AND 80;

SELECT ORDER_PEOPLE, ORDER_ITEM, COUNT FROM ORDER ORDER BY ORDER_PEOPLE ASC, COUNT DESC;

SELECT S.A, S.B, T.D FROM S LEFT OUTER JOIN T ON S.B = T.C;

SELECT R1.A, R2.B, R2.C FROM R2 RIGHT OUTER JOIN R1 ON R1.B = R2.B;

SELECT FIELD_LIST FROM TABLE1 INNER JOIN TABLE2 ON TABLE1.FIELD = TABLE2.FIELD;

SELECT NAME, ADDR FROM COMPANY WHERE CITY IN ('SEOUL', 'SUWON');

SELECT * FROM EMPLOYEE WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DEPTNAME = 'INSA');

SELECT * FROM ITEM WHERE PRICE > ANY (SELECT PRICE FROM ITEM WHERE COMPANY = 'B');

SELECT NAME FROM EMPLOYEE WHERE EXISTS ( SELECT * FROM DEPT WHERE EMPLOYEE.DEPTNO = DEPT.DEPTNO AND 
DEPTNAME='SALES' OR DEPTNAME='DEVELOPMENT');

SELECT NAME FROM EMPLOYEE WHERE NOT EXISTS (SELECT * FROM DEPENDENT WHERE EMPLOYEE.SSN = DEPENDENT.SSN);

SELECT NAME, SALARY FROM EMPLOYEE WHERE DEPTNO IN ( SELECT DEPTNO FROM EMPLOYEE GROUP BY DEPTNO 
HAVING COUNT(*) >= 2);

SELECT NAME, SALARY FROM EMPLOYEE WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEE);

SELECT NAME, AVG(SCORE) FROM GRADE GROUP BY NAME;

SELECT DEPTNAME, AVG(SALARY) FROM EMPLOYEE GROUP BY DEPTNAME HAVING COUNT(*) > = 7;

SELECT DEPTNAME, AVG(SALARY) FROM EMPLOYEE GROUP BY DEPTNAME HAVING AVG(SALARY) > 6900;

SELECT count(*) as CNT FROM student GROUP BY HAVING COUNT(B) = 2;

SELECT count(*) as CNT FROM ( SELECT count(*) From student GROUP BY subject HAVING count(*) > 2);

SELECT DEGREE, AVG(SALARY) AS SAL_AVG, SUM(SALARY) AS SAL_TOTAL FROM EMPLOYEE GROUP BY DEGREE
ORDER BY SAL_AVG DESC;

SELECT DEPTNO, count(*) AS CNT FROM EMPLOYEE WHERE SALARY > 20000 AND DEPTNO IN (
    SELECT DEPTNO FROM EMPLOYEE GROUP BY DEPTNO HAVING count(*) >= 2
) GROUP BY DEPTNO;


